version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - npm pkg delete scripts.prepare
      - yarn install --lock-file

  build:
    commands:
      - yarn build
